[font]

normal.family = "Hack Nerd Font"
bold.family = "Hack Nerd Font"
italic.family = "Hack Nerd Font"
bold_italic.family = "Hack Nerd Font"

size = 14.0

[window]
decorations = "None"
startup_mode = "Maximized"
